// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: monitor_info.proto

#include "monitor_info.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
extern PROTOBUF_INTERNAL_EXPORT_cpu_5fload_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_CpuLoad_cpu_5fload_2eproto;
extern PROTOBUF_INTERNAL_EXPORT_cpu_5fsoftirq_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_CpuSoftirqs_cpu_5fsoftirq_2eproto;
extern PROTOBUF_INTERNAL_EXPORT_cpu_5fstat_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_CpuStat_cpu_5fstat_2eproto;
extern PROTOBUF_INTERNAL_EXPORT_mem_5finfo_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_MemInfo_mem_5finfo_2eproto;
extern PROTOBUF_INTERNAL_EXPORT_net_5finfo_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_NetInfo_net_5finfo_2eproto;
namespace monitor {
namespace proto {
class MonitorInfoDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<MonitorInfo> _instance;
} _MonitorInfo_default_instance_;
class CodeDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<Code> _instance;
} _Code_default_instance_;
class machineDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<machine> _instance;
} _machine_default_instance_;
}  // namespace proto
}  // namespace monitor
static void InitDefaultsscc_info_Code_monitor_5finfo_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::monitor::proto::_Code_default_instance_;
    new (ptr) ::monitor::proto::Code();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::monitor::proto::Code::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_Code_monitor_5finfo_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_Code_monitor_5finfo_2eproto}, {}};

static void InitDefaultsscc_info_MonitorInfo_monitor_5finfo_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::monitor::proto::_MonitorInfo_default_instance_;
    new (ptr) ::monitor::proto::MonitorInfo();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::monitor::proto::MonitorInfo::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<5> scc_info_MonitorInfo_monitor_5finfo_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 5, 0, InitDefaultsscc_info_MonitorInfo_monitor_5finfo_2eproto}, {
      &scc_info_CpuSoftirqs_cpu_5fsoftirq_2eproto.base,
      &scc_info_CpuLoad_cpu_5fload_2eproto.base,
      &scc_info_CpuStat_cpu_5fstat_2eproto.base,
      &scc_info_MemInfo_mem_5finfo_2eproto.base,
      &scc_info_NetInfo_net_5finfo_2eproto.base,}};

static void InitDefaultsscc_info_machine_monitor_5finfo_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::monitor::proto::_machine_default_instance_;
    new (ptr) ::monitor::proto::machine();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::monitor::proto::machine::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_machine_monitor_5finfo_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_machine_monitor_5finfo_2eproto}, {}};

static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_monitor_5finfo_2eproto[3];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_monitor_5finfo_2eproto = nullptr;
static const ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor* file_level_service_descriptors_monitor_5finfo_2eproto[1];

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_monitor_5finfo_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::monitor::proto::MonitorInfo, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::monitor::proto::MonitorInfo, name_),
  PROTOBUF_FIELD_OFFSET(::monitor::proto::MonitorInfo, soft_irq_),
  PROTOBUF_FIELD_OFFSET(::monitor::proto::MonitorInfo, cpu_load_),
  PROTOBUF_FIELD_OFFSET(::monitor::proto::MonitorInfo, cpu_stat_),
  PROTOBUF_FIELD_OFFSET(::monitor::proto::MonitorInfo, mem_info_),
  PROTOBUF_FIELD_OFFSET(::monitor::proto::MonitorInfo, net_info_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::monitor::proto::Code, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::monitor::proto::Code, code_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::monitor::proto::machine, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::monitor::proto::machine, name_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::monitor::proto::MonitorInfo)},
  { 11, -1, sizeof(::monitor::proto::Code)},
  { 17, -1, sizeof(::monitor::proto::machine)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::monitor::proto::_MonitorInfo_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::monitor::proto::_Code_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::monitor::proto::_machine_default_instance_),
};

const char descriptor_table_protodef_monitor_5finfo_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\022monitor_info.proto\022\rmonitor.proto\032\016cpu"
  "_load.proto\032\021cpu_softirq.proto\032\016cpu_stat"
  ".proto\032\016mem_info.proto\032\016net_info.proto\"\361"
  "\001\n\013MonitorInfo\022\014\n\004name\030\001 \001(\t\022,\n\010soft_irq"
  "\030\002 \003(\0132\032.monitor.proto.CpuSoftirqs\022(\n\010cp"
  "u_load\030\003 \001(\0132\026.monitor.proto.CpuLoad\022(\n\010"
  "cpu_stat\030\004 \003(\0132\026.monitor.proto.CpuStat\022("
  "\n\010mem_info\030\005 \001(\0132\026.monitor.proto.MemInfo"
  "\022(\n\010net_info\030\006 \003(\0132\026.monitor.proto.NetIn"
  "fo\"\024\n\004Code\022\014\n\004code\030\001 \001(\005\"\027\n\007machine\022\014\n\004n"
  "ame\030\001 \001(\t2\231\001\n\nRpcManager\022C\n\016SetMonitorIn"
  "fo\022\032.monitor.proto.MonitorInfo\032\023.monitor"
  ".proto.Code\"\000\022F\n\016GetMonitorInfo\022\026.monito"
  "r.proto.machine\032\032.monitor.proto.MonitorI"
  "nfo\"\000B\003\200\001\001b\006proto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_monitor_5finfo_2eproto_deps[5] = {
  &::descriptor_table_cpu_5fload_2eproto,
  &::descriptor_table_cpu_5fsoftirq_2eproto,
  &::descriptor_table_cpu_5fstat_2eproto,
  &::descriptor_table_mem_5finfo_2eproto,
  &::descriptor_table_net_5finfo_2eproto,
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_monitor_5finfo_2eproto_sccs[3] = {
  &scc_info_Code_monitor_5finfo_2eproto.base,
  &scc_info_MonitorInfo_monitor_5finfo_2eproto.base,
  &scc_info_machine_monitor_5finfo_2eproto.base,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_monitor_5finfo_2eproto_once;
static bool descriptor_table_monitor_5finfo_2eproto_initialized = false;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_monitor_5finfo_2eproto = {
  &descriptor_table_monitor_5finfo_2eproto_initialized, descriptor_table_protodef_monitor_5finfo_2eproto, "monitor_info.proto", 578,
  &descriptor_table_monitor_5finfo_2eproto_once, descriptor_table_monitor_5finfo_2eproto_sccs, descriptor_table_monitor_5finfo_2eproto_deps, 3, 5,
  schemas, file_default_instances, TableStruct_monitor_5finfo_2eproto::offsets,
  file_level_metadata_monitor_5finfo_2eproto, 3, file_level_enum_descriptors_monitor_5finfo_2eproto, file_level_service_descriptors_monitor_5finfo_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_monitor_5finfo_2eproto = (  ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_monitor_5finfo_2eproto), true);
namespace monitor {
namespace proto {

// ===================================================================

void MonitorInfo::InitAsDefaultInstance() {
  ::monitor::proto::_MonitorInfo_default_instance_._instance.get_mutable()->cpu_load_ = const_cast< ::monitor::proto::CpuLoad*>(
      ::monitor::proto::CpuLoad::internal_default_instance());
  ::monitor::proto::_MonitorInfo_default_instance_._instance.get_mutable()->mem_info_ = const_cast< ::monitor::proto::MemInfo*>(
      ::monitor::proto::MemInfo::internal_default_instance());
}
class MonitorInfo::_Internal {
 public:
  static const ::monitor::proto::CpuLoad& cpu_load(const MonitorInfo* msg);
  static const ::monitor::proto::MemInfo& mem_info(const MonitorInfo* msg);
};

const ::monitor::proto::CpuLoad&
MonitorInfo::_Internal::cpu_load(const MonitorInfo* msg) {
  return *msg->cpu_load_;
}
const ::monitor::proto::MemInfo&
MonitorInfo::_Internal::mem_info(const MonitorInfo* msg) {
  return *msg->mem_info_;
}
void MonitorInfo::clear_soft_irq() {
  soft_irq_.Clear();
}
void MonitorInfo::clear_cpu_load() {
  if (GetArenaNoVirtual() == nullptr && cpu_load_ != nullptr) {
    delete cpu_load_;
  }
  cpu_load_ = nullptr;
}
void MonitorInfo::clear_cpu_stat() {
  cpu_stat_.Clear();
}
void MonitorInfo::clear_mem_info() {
  if (GetArenaNoVirtual() == nullptr && mem_info_ != nullptr) {
    delete mem_info_;
  }
  mem_info_ = nullptr;
}
void MonitorInfo::clear_net_info() {
  net_info_.Clear();
}
MonitorInfo::MonitorInfo()
  : ::PROTOBUF_NAMESPACE_ID::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:monitor.proto.MonitorInfo)
}
MonitorInfo::MonitorInfo(const MonitorInfo& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _internal_metadata_(nullptr),
      soft_irq_(from.soft_irq_),
      cpu_stat_(from.cpu_stat_),
      net_info_(from.net_info_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  name_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_name().empty()) {
    name_.AssignWithDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from.name_);
  }
  if (from._internal_has_cpu_load()) {
    cpu_load_ = new ::monitor::proto::CpuLoad(*from.cpu_load_);
  } else {
    cpu_load_ = nullptr;
  }
  if (from._internal_has_mem_info()) {
    mem_info_ = new ::monitor::proto::MemInfo(*from.mem_info_);
  } else {
    mem_info_ = nullptr;
  }
  // @@protoc_insertion_point(copy_constructor:monitor.proto.MonitorInfo)
}

void MonitorInfo::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_MonitorInfo_monitor_5finfo_2eproto.base);
  name_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  ::memset(&cpu_load_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&mem_info_) -
      reinterpret_cast<char*>(&cpu_load_)) + sizeof(mem_info_));
}

MonitorInfo::~MonitorInfo() {
  // @@protoc_insertion_point(destructor:monitor.proto.MonitorInfo)
  SharedDtor();
}

void MonitorInfo::SharedDtor() {
  name_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (this != internal_default_instance()) delete cpu_load_;
  if (this != internal_default_instance()) delete mem_info_;
}

void MonitorInfo::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const MonitorInfo& MonitorInfo::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_MonitorInfo_monitor_5finfo_2eproto.base);
  return *internal_default_instance();
}


void MonitorInfo::Clear() {
// @@protoc_insertion_point(message_clear_start:monitor.proto.MonitorInfo)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  soft_irq_.Clear();
  cpu_stat_.Clear();
  net_info_.Clear();
  name_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (GetArenaNoVirtual() == nullptr && cpu_load_ != nullptr) {
    delete cpu_load_;
  }
  cpu_load_ = nullptr;
  if (GetArenaNoVirtual() == nullptr && mem_info_ != nullptr) {
    delete mem_info_;
  }
  mem_info_ = nullptr;
  _internal_metadata_.Clear();
}

const char* MonitorInfo::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // string name = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          auto str = _internal_mutable_name();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "monitor.proto.MonitorInfo.name"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // repeated .monitor.proto.CpuSoftirqs soft_irq = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_soft_irq(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<18>(ptr));
        } else goto handle_unusual;
        continue;
      // .monitor.proto.CpuLoad cpu_load = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 26)) {
          ptr = ctx->ParseMessage(_internal_mutable_cpu_load(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // repeated .monitor.proto.CpuStat cpu_stat = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 34)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_cpu_stat(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<34>(ptr));
        } else goto handle_unusual;
        continue;
      // .monitor.proto.MemInfo mem_info = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 42)) {
          ptr = ctx->ParseMessage(_internal_mutable_mem_info(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // repeated .monitor.proto.NetInfo net_info = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 50)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_net_info(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<50>(ptr));
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag, &_internal_metadata_, ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* MonitorInfo::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:monitor.proto.MonitorInfo)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string name = 1;
  if (this->name().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_name().data(), static_cast<int>(this->_internal_name().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "monitor.proto.MonitorInfo.name");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_name(), target);
  }

  // repeated .monitor.proto.CpuSoftirqs soft_irq = 2;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->_internal_soft_irq_size()); i < n; i++) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(2, this->_internal_soft_irq(i), target, stream);
  }

  // .monitor.proto.CpuLoad cpu_load = 3;
  if (this->has_cpu_load()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        3, _Internal::cpu_load(this), target, stream);
  }

  // repeated .monitor.proto.CpuStat cpu_stat = 4;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->_internal_cpu_stat_size()); i < n; i++) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(4, this->_internal_cpu_stat(i), target, stream);
  }

  // .monitor.proto.MemInfo mem_info = 5;
  if (this->has_mem_info()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        5, _Internal::mem_info(this), target, stream);
  }

  // repeated .monitor.proto.NetInfo net_info = 6;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->_internal_net_info_size()); i < n; i++) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(6, this->_internal_net_info(i), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:monitor.proto.MonitorInfo)
  return target;
}

size_t MonitorInfo::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:monitor.proto.MonitorInfo)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .monitor.proto.CpuSoftirqs soft_irq = 2;
  total_size += 1UL * this->_internal_soft_irq_size();
  for (const auto& msg : this->soft_irq_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // repeated .monitor.proto.CpuStat cpu_stat = 4;
  total_size += 1UL * this->_internal_cpu_stat_size();
  for (const auto& msg : this->cpu_stat_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // repeated .monitor.proto.NetInfo net_info = 6;
  total_size += 1UL * this->_internal_net_info_size();
  for (const auto& msg : this->net_info_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // string name = 1;
  if (this->name().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_name());
  }

  // .monitor.proto.CpuLoad cpu_load = 3;
  if (this->has_cpu_load()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *cpu_load_);
  }

  // .monitor.proto.MemInfo mem_info = 5;
  if (this->has_mem_info()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *mem_info_);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void MonitorInfo::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:monitor.proto.MonitorInfo)
  GOOGLE_DCHECK_NE(&from, this);
  const MonitorInfo* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<MonitorInfo>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:monitor.proto.MonitorInfo)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:monitor.proto.MonitorInfo)
    MergeFrom(*source);
  }
}

void MonitorInfo::MergeFrom(const MonitorInfo& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:monitor.proto.MonitorInfo)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  soft_irq_.MergeFrom(from.soft_irq_);
  cpu_stat_.MergeFrom(from.cpu_stat_);
  net_info_.MergeFrom(from.net_info_);
  if (from.name().size() > 0) {

    name_.AssignWithDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from.name_);
  }
  if (from.has_cpu_load()) {
    _internal_mutable_cpu_load()->::monitor::proto::CpuLoad::MergeFrom(from._internal_cpu_load());
  }
  if (from.has_mem_info()) {
    _internal_mutable_mem_info()->::monitor::proto::MemInfo::MergeFrom(from._internal_mem_info());
  }
}

void MonitorInfo::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:monitor.proto.MonitorInfo)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void MonitorInfo::CopyFrom(const MonitorInfo& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:monitor.proto.MonitorInfo)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MonitorInfo::IsInitialized() const {
  return true;
}

void MonitorInfo::InternalSwap(MonitorInfo* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  soft_irq_.InternalSwap(&other->soft_irq_);
  cpu_stat_.InternalSwap(&other->cpu_stat_);
  net_info_.InternalSwap(&other->net_info_);
  name_.Swap(&other->name_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(cpu_load_, other->cpu_load_);
  swap(mem_info_, other->mem_info_);
}

::PROTOBUF_NAMESPACE_ID::Metadata MonitorInfo::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

void Code::InitAsDefaultInstance() {
}
class Code::_Internal {
 public:
};

Code::Code()
  : ::PROTOBUF_NAMESPACE_ID::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:monitor.proto.Code)
}
Code::Code(const Code& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _internal_metadata_(nullptr) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  code_ = from.code_;
  // @@protoc_insertion_point(copy_constructor:monitor.proto.Code)
}

void Code::SharedCtor() {
  code_ = 0;
}

Code::~Code() {
  // @@protoc_insertion_point(destructor:monitor.proto.Code)
  SharedDtor();
}

void Code::SharedDtor() {
}

void Code::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const Code& Code::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_Code_monitor_5finfo_2eproto.base);
  return *internal_default_instance();
}


void Code::Clear() {
// @@protoc_insertion_point(message_clear_start:monitor.proto.Code)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  code_ = 0;
  _internal_metadata_.Clear();
}

const char* Code::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // int32 code = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          code_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag, &_internal_metadata_, ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* Code::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:monitor.proto.Code)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 code = 1;
  if (this->code() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(1, this->_internal_code(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:monitor.proto.Code)
  return target;
}

size_t Code::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:monitor.proto.Code)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // int32 code = 1;
  if (this->code() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
        this->_internal_code());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void Code::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:monitor.proto.Code)
  GOOGLE_DCHECK_NE(&from, this);
  const Code* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<Code>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:monitor.proto.Code)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:monitor.proto.Code)
    MergeFrom(*source);
  }
}

void Code::MergeFrom(const Code& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:monitor.proto.Code)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.code() != 0) {
    _internal_set_code(from._internal_code());
  }
}

void Code::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:monitor.proto.Code)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Code::CopyFrom(const Code& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:monitor.proto.Code)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Code::IsInitialized() const {
  return true;
}

void Code::InternalSwap(Code* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(code_, other->code_);
}

::PROTOBUF_NAMESPACE_ID::Metadata Code::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

void machine::InitAsDefaultInstance() {
}
class machine::_Internal {
 public:
};

machine::machine()
  : ::PROTOBUF_NAMESPACE_ID::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:monitor.proto.machine)
}
machine::machine(const machine& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _internal_metadata_(nullptr) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  name_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_name().empty()) {
    name_.AssignWithDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from.name_);
  }
  // @@protoc_insertion_point(copy_constructor:monitor.proto.machine)
}

void machine::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_machine_monitor_5finfo_2eproto.base);
  name_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

machine::~machine() {
  // @@protoc_insertion_point(destructor:monitor.proto.machine)
  SharedDtor();
}

void machine::SharedDtor() {
  name_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void machine::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const machine& machine::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_machine_monitor_5finfo_2eproto.base);
  return *internal_default_instance();
}


void machine::Clear() {
// @@protoc_insertion_point(message_clear_start:monitor.proto.machine)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  name_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  _internal_metadata_.Clear();
}

const char* machine::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // string name = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          auto str = _internal_mutable_name();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "monitor.proto.machine.name"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag, &_internal_metadata_, ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* machine::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:monitor.proto.machine)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string name = 1;
  if (this->name().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_name().data(), static_cast<int>(this->_internal_name().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "monitor.proto.machine.name");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_name(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:monitor.proto.machine)
  return target;
}

size_t machine::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:monitor.proto.machine)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string name = 1;
  if (this->name().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_name());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void machine::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:monitor.proto.machine)
  GOOGLE_DCHECK_NE(&from, this);
  const machine* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<machine>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:monitor.proto.machine)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:monitor.proto.machine)
    MergeFrom(*source);
  }
}

void machine::MergeFrom(const machine& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:monitor.proto.machine)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.name().size() > 0) {

    name_.AssignWithDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from.name_);
  }
}

void machine::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:monitor.proto.machine)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void machine::CopyFrom(const machine& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:monitor.proto.machine)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool machine::IsInitialized() const {
  return true;
}

void machine::InternalSwap(machine* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  name_.Swap(&other->name_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
}

::PROTOBUF_NAMESPACE_ID::Metadata machine::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

RpcManager::~RpcManager() {}

const ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor* RpcManager::descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_monitor_5finfo_2eproto);
  return file_level_service_descriptors_monitor_5finfo_2eproto[0];
}

const ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor* RpcManager::GetDescriptor() {
  return descriptor();
}

void RpcManager::SetMonitorInfo(::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                         const ::monitor::proto::MonitorInfo*,
                         ::monitor::proto::Code*,
                         ::google::protobuf::Closure* done) {
  controller->SetFailed("Method SetMonitorInfo() not implemented.");
  done->Run();
}

void RpcManager::GetMonitorInfo(::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                         const ::monitor::proto::machine*,
                         ::monitor::proto::MonitorInfo*,
                         ::google::protobuf::Closure* done) {
  controller->SetFailed("Method GetMonitorInfo() not implemented.");
  done->Run();
}

void RpcManager::CallMethod(const ::PROTOBUF_NAMESPACE_ID::MethodDescriptor* method,
                             ::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                             const ::PROTOBUF_NAMESPACE_ID::Message* request,
                             ::PROTOBUF_NAMESPACE_ID::Message* response,
                             ::google::protobuf::Closure* done) {
  GOOGLE_DCHECK_EQ(method->service(), file_level_service_descriptors_monitor_5finfo_2eproto[0]);
  switch(method->index()) {
    case 0:
      SetMonitorInfo(controller,
             ::PROTOBUF_NAMESPACE_ID::internal::DownCast<const ::monitor::proto::MonitorInfo*>(
                 request),
             ::PROTOBUF_NAMESPACE_ID::internal::DownCast<::monitor::proto::Code*>(
                 response),
             done);
      break;
    case 1:
      GetMonitorInfo(controller,
             ::PROTOBUF_NAMESPACE_ID::internal::DownCast<const ::monitor::proto::machine*>(
                 request),
             ::PROTOBUF_NAMESPACE_ID::internal::DownCast<::monitor::proto::MonitorInfo*>(
                 response),
             done);
      break;
    default:
      GOOGLE_LOG(FATAL) << "Bad method index; this should never happen.";
      break;
  }
}

const ::PROTOBUF_NAMESPACE_ID::Message& RpcManager::GetRequestPrototype(
    const ::PROTOBUF_NAMESPACE_ID::MethodDescriptor* method) const {
  GOOGLE_DCHECK_EQ(method->service(), descriptor());
  switch(method->index()) {
    case 0:
      return ::monitor::proto::MonitorInfo::default_instance();
    case 1:
      return ::monitor::proto::machine::default_instance();
    default:
      GOOGLE_LOG(FATAL) << "Bad method index; this should never happen.";
      return *::PROTOBUF_NAMESPACE_ID::MessageFactory::generated_factory()
          ->GetPrototype(method->input_type());
  }
}

const ::PROTOBUF_NAMESPACE_ID::Message& RpcManager::GetResponsePrototype(
    const ::PROTOBUF_NAMESPACE_ID::MethodDescriptor* method) const {
  GOOGLE_DCHECK_EQ(method->service(), descriptor());
  switch(method->index()) {
    case 0:
      return ::monitor::proto::Code::default_instance();
    case 1:
      return ::monitor::proto::MonitorInfo::default_instance();
    default:
      GOOGLE_LOG(FATAL) << "Bad method index; this should never happen.";
      return *::PROTOBUF_NAMESPACE_ID::MessageFactory::generated_factory()
          ->GetPrototype(method->output_type());
  }
}

RpcManager_Stub::RpcManager_Stub(::PROTOBUF_NAMESPACE_ID::RpcChannel* channel)
  : channel_(channel), owns_channel_(false) {}
RpcManager_Stub::RpcManager_Stub(
    ::PROTOBUF_NAMESPACE_ID::RpcChannel* channel,
    ::PROTOBUF_NAMESPACE_ID::Service::ChannelOwnership ownership)
  : channel_(channel),
    owns_channel_(ownership == ::PROTOBUF_NAMESPACE_ID::Service::STUB_OWNS_CHANNEL) {}
RpcManager_Stub::~RpcManager_Stub() {
  if (owns_channel_) delete channel_;
}

void RpcManager_Stub::SetMonitorInfo(::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                              const ::monitor::proto::MonitorInfo* request,
                              ::monitor::proto::Code* response,
                              ::google::protobuf::Closure* done) {
  channel_->CallMethod(descriptor()->method(0),
                       controller, request, response, done);
}
void RpcManager_Stub::GetMonitorInfo(::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                              const ::monitor::proto::machine* request,
                              ::monitor::proto::MonitorInfo* response,
                              ::google::protobuf::Closure* done) {
  channel_->CallMethod(descriptor()->method(1),
                       controller, request, response, done);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace proto
}  // namespace monitor
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::monitor::proto::MonitorInfo* Arena::CreateMaybeMessage< ::monitor::proto::MonitorInfo >(Arena* arena) {
  return Arena::CreateInternal< ::monitor::proto::MonitorInfo >(arena);
}
template<> PROTOBUF_NOINLINE ::monitor::proto::Code* Arena::CreateMaybeMessage< ::monitor::proto::Code >(Arena* arena) {
  return Arena::CreateInternal< ::monitor::proto::Code >(arena);
}
template<> PROTOBUF_NOINLINE ::monitor::proto::machine* Arena::CreateMaybeMessage< ::monitor::proto::machine >(Arena* arena) {
  return Arena::CreateInternal< ::monitor::proto::machine >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
