// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: net_info.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_net_5finfo_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_net_5finfo_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3011000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3011000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_net_5finfo_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_net_5finfo_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_net_5finfo_2eproto;
namespace monitor {
namespace proto {
class NetInfo;
class NetInfoDefaultTypeInternal;
extern NetInfoDefaultTypeInternal _NetInfo_default_instance_;
}  // namespace proto
}  // namespace monitor
PROTOBUF_NAMESPACE_OPEN
template<> ::monitor::proto::NetInfo* Arena::CreateMaybeMessage<::monitor::proto::NetInfo>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace monitor {
namespace proto {

// ===================================================================

class NetInfo :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:monitor.proto.NetInfo) */ {
 public:
  NetInfo();
  virtual ~NetInfo();

  NetInfo(const NetInfo& from);
  NetInfo(NetInfo&& from) noexcept
    : NetInfo() {
    *this = ::std::move(from);
  }

  inline NetInfo& operator=(const NetInfo& from) {
    CopyFrom(from);
    return *this;
  }
  inline NetInfo& operator=(NetInfo&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const NetInfo& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const NetInfo* internal_default_instance() {
    return reinterpret_cast<const NetInfo*>(
               &_NetInfo_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(NetInfo& a, NetInfo& b) {
    a.Swap(&b);
  }
  inline void Swap(NetInfo* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline NetInfo* New() const final {
    return CreateMaybeMessage<NetInfo>(nullptr);
  }

  NetInfo* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<NetInfo>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const NetInfo& from);
  void MergeFrom(const NetInfo& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(NetInfo* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "monitor.proto.NetInfo";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_net_5finfo_2eproto);
    return ::descriptor_table_net_5finfo_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kNameFieldNumber = 1,
    kSendRateFieldNumber = 2,
    kRecvRateFieldNumber = 3,
    kSendPacketsRateFieldNumber = 4,
    kRecvPacketsRateFieldNumber = 5,
  };
  // string name = 1;
  void clear_name();
  const std::string& name() const;
  void set_name(const std::string& value);
  void set_name(std::string&& value);
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  std::string* mutable_name();
  std::string* release_name();
  void set_allocated_name(std::string* name);
  private:
  const std::string& _internal_name() const;
  void _internal_set_name(const std::string& value);
  std::string* _internal_mutable_name();
  public:

  // float send_rate = 2;
  void clear_send_rate();
  float send_rate() const;
  void set_send_rate(float value);
  private:
  float _internal_send_rate() const;
  void _internal_set_send_rate(float value);
  public:

  // float recv_rate = 3;
  void clear_recv_rate();
  float recv_rate() const;
  void set_recv_rate(float value);
  private:
  float _internal_recv_rate() const;
  void _internal_set_recv_rate(float value);
  public:

  // float send_packets_rate = 4;
  void clear_send_packets_rate();
  float send_packets_rate() const;
  void set_send_packets_rate(float value);
  private:
  float _internal_send_packets_rate() const;
  void _internal_set_send_packets_rate(float value);
  public:

  // float recv_packets_rate = 5;
  void clear_recv_packets_rate();
  float recv_packets_rate() const;
  void set_recv_packets_rate(float value);
  private:
  float _internal_recv_packets_rate() const;
  void _internal_set_recv_packets_rate(float value);
  public:

  // @@protoc_insertion_point(class_scope:monitor.proto.NetInfo)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr name_;
  float send_rate_;
  float recv_rate_;
  float send_packets_rate_;
  float recv_packets_rate_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_net_5finfo_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// NetInfo

// string name = 1;
inline void NetInfo::clear_name() {
  name_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& NetInfo::name() const {
  // @@protoc_insertion_point(field_get:monitor.proto.NetInfo.name)
  return _internal_name();
}
inline void NetInfo::set_name(const std::string& value) {
  _internal_set_name(value);
  // @@protoc_insertion_point(field_set:monitor.proto.NetInfo.name)
}
inline std::string* NetInfo::mutable_name() {
  // @@protoc_insertion_point(field_mutable:monitor.proto.NetInfo.name)
  return _internal_mutable_name();
}
inline const std::string& NetInfo::_internal_name() const {
  return name_.GetNoArena();
}
inline void NetInfo::_internal_set_name(const std::string& value) {
  
  name_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
}
inline void NetInfo::set_name(std::string&& value) {
  
  name_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:monitor.proto.NetInfo.name)
}
inline void NetInfo::set_name(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  name_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:monitor.proto.NetInfo.name)
}
inline void NetInfo::set_name(const char* value, size_t size) {
  
  name_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:monitor.proto.NetInfo.name)
}
inline std::string* NetInfo::_internal_mutable_name() {
  
  return name_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* NetInfo::release_name() {
  // @@protoc_insertion_point(field_release:monitor.proto.NetInfo.name)
  
  return name_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void NetInfo::set_allocated_name(std::string* name) {
  if (name != nullptr) {
    
  } else {
    
  }
  name_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:monitor.proto.NetInfo.name)
}

// float send_rate = 2;
inline void NetInfo::clear_send_rate() {
  send_rate_ = 0;
}
inline float NetInfo::_internal_send_rate() const {
  return send_rate_;
}
inline float NetInfo::send_rate() const {
  // @@protoc_insertion_point(field_get:monitor.proto.NetInfo.send_rate)
  return _internal_send_rate();
}
inline void NetInfo::_internal_set_send_rate(float value) {
  
  send_rate_ = value;
}
inline void NetInfo::set_send_rate(float value) {
  _internal_set_send_rate(value);
  // @@protoc_insertion_point(field_set:monitor.proto.NetInfo.send_rate)
}

// float recv_rate = 3;
inline void NetInfo::clear_recv_rate() {
  recv_rate_ = 0;
}
inline float NetInfo::_internal_recv_rate() const {
  return recv_rate_;
}
inline float NetInfo::recv_rate() const {
  // @@protoc_insertion_point(field_get:monitor.proto.NetInfo.recv_rate)
  return _internal_recv_rate();
}
inline void NetInfo::_internal_set_recv_rate(float value) {
  
  recv_rate_ = value;
}
inline void NetInfo::set_recv_rate(float value) {
  _internal_set_recv_rate(value);
  // @@protoc_insertion_point(field_set:monitor.proto.NetInfo.recv_rate)
}

// float send_packets_rate = 4;
inline void NetInfo::clear_send_packets_rate() {
  send_packets_rate_ = 0;
}
inline float NetInfo::_internal_send_packets_rate() const {
  return send_packets_rate_;
}
inline float NetInfo::send_packets_rate() const {
  // @@protoc_insertion_point(field_get:monitor.proto.NetInfo.send_packets_rate)
  return _internal_send_packets_rate();
}
inline void NetInfo::_internal_set_send_packets_rate(float value) {
  
  send_packets_rate_ = value;
}
inline void NetInfo::set_send_packets_rate(float value) {
  _internal_set_send_packets_rate(value);
  // @@protoc_insertion_point(field_set:monitor.proto.NetInfo.send_packets_rate)
}

// float recv_packets_rate = 5;
inline void NetInfo::clear_recv_packets_rate() {
  recv_packets_rate_ = 0;
}
inline float NetInfo::_internal_recv_packets_rate() const {
  return recv_packets_rate_;
}
inline float NetInfo::recv_packets_rate() const {
  // @@protoc_insertion_point(field_get:monitor.proto.NetInfo.recv_packets_rate)
  return _internal_recv_packets_rate();
}
inline void NetInfo::_internal_set_recv_packets_rate(float value) {
  
  recv_packets_rate_ = value;
}
inline void NetInfo::set_recv_packets_rate(float value) {
  _internal_set_recv_packets_rate(value);
  // @@protoc_insertion_point(field_set:monitor.proto.NetInfo.recv_packets_rate)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace proto
}  // namespace monitor

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_net_5finfo_2eproto
